package com.d3if0002.currex.model

data class Country (
    val name: Map<String, Any>,
    val tld: List<String>,
    val cca2: String,
    val ccn3: String,
    val cca3: String,
    val cioc: String,
    val independent: Boolean,
    val status: String,
    val unMember: Boolean,
    val currencies: Map<String, Any>,
    val idd: Map<String, Any>,
    val capitcal: List<String>,
    val altSpellings: List<String>,
    val region: String,
    val subregion: String,
    val languages: Map<String, Any>,
    val translations: Map<String, Any>,
    val latlng: List<Double>,
    val landlocked: Boolean,
    val borders: List<String>,
    val area: Double,
    val demonyms: Map<String, Any>,
    val flag: String,
    val maps: Map<String, Any>,
    val population: Int,
    val gini: Map<String, Any>,
    val fifa: String,
    val car: Map<String, Any>,
    val timezones: List<String>,
    val continents: List<String>,
    val flags: Map<String, Any>,
    val coatOfArms: Map<String, Any>,
    val startOfWeek: String,
    val capitalInfo: Map<String, Any>
)
